export const Teams = [
  // 🏀 Eastern Conference
  // Atlantic Division
  {
    id: 1,
    conference: "Eastern",
    division: "Atlantic",
    title: "Boston Celtics",
    win: 85.2,
    offense: 94,
    defence: 89,
    pt: 78.5,
    ast: 82.3,
    reb: 75.8,
    icon: "/assets/starIcon.png",
    iconSrc: "/assets/dot.png",
    Img: "/assets/boston_celtics.png",
  },
  {
    id: 2,
    conference: "Eastern",
    division: "Atlantic",
    title: "Brooklyn Nets",
    win: 64.1,
    offense: 88,
    defence: 84,
    pt: 72.4,
    ast: 76.9,
    reb: 70.2,
    icon: "/assets/starIcon.png",
    iconSrc: "/assets/dot.png",
    Img: "/assets/Brooklyn_Nets.png",
  },
  {
    id: 3,
    conference: "Eastern",
    division: "Atlantic",
    title: "New York Knicks",
    win: 70.5,
    offense: 90,
    defence: 86,
    pt: 74.2,
    ast: 78.1,
    reb: 73.4,
    icon: "/assets/starIcon.png",
    iconSrc: "/assets/dot.png",
    Img: "/assets/New_York_Knicks.png",
  },
  {
    id: 4,
    conference: "Eastern",
    division: "Atlantic",
    title: "Philadelphia 76ers",
    win: 72.3,
    offense: 91,
    defence: 85,
    pt: 75.1,
    ast: 80.5,
    reb: 72.8,
    icon: "/assets/starIcon.png",
    iconSrc: "/assets/dot.png",
    Img: "/assets/Philadelphia_76ers.png",
  },
  {
    id: 5,
    conference: "Eastern",
    division: "Atlantic",
    title: "Toronto Raptors",
    win: 60.7,
    offense: 85,
    defence: 81,
    pt: 69.8,
    ast: 74.2,
    reb: 71.5,
    icon: "/assets/starIcon.png",
    iconSrc: "/assets/dot.png",
    Img: "/assets/Toronto_Raptors.png",
  },

  // Central Division
  {
    id: 6,
    conference: "Eastern",
    division: "Central",
    title: "Chicago Bulls",
    win: 66.4,
    offense: 86,
    defence: 82,
    pt: 71.9,
    ast: 75.8,
    reb: 70.6,
    icon: "/assets/starIcon.png",
    iconSrc: "/assets/dot.png",
    Img: "/assets/Chicago_Bulls.png",
  },
  {
    id: 7,
    conference: "Eastern",
    division: "Central",
    title: "Cleveland Cavaliers",
    win: 75.8,
    offense: 92,
    defence: 88,
    pt: 77.2,
    ast: 81.1,
    reb: 74.6,
    icon: "/assets/starIcon.png",
    iconSrc: "/assets/dot.png",
    Img: "/assets/Cleveland_Cavaliers.jpeg",
  },
  {
    id: 8,
    conference: "Eastern",
    division: "Central",
    title: "Detroit Pistons",
    win: 52.3,
    offense: 80,
    defence: 78,
    pt: 65.4,
    ast: 70.8,
    reb: 68.2,
    icon: "/assets/starIcon.png",
    iconSrc: "/assets/dot.png",
    Img: "/assets/Detroit_Pistons.png",
  },
  {
    id: 9,
    conference: "Eastern",
    division: "Central",
    title: "Indiana Pacers",
    win: 68.2,
    offense: 89,
    defence: 83,
    pt: 73.1,
    ast: 79.4,
    reb: 72.0,
    icon: "/assets/starIcon.png",
    iconSrc: "/assets/dot.png",
    Img: "/assets/Indiana_Pacers.png",
  },
  {
    id: 10,
    conference: "Eastern",
    division: "Central",
    title: "Milwaukee Bucks",
    win: 74.6,
    offense: 91,
    defence: 87,
    pt: 76.8,
    ast: 80.2,
    reb: 73.9,
    icon: "/assets/starIcon.png",
    iconSrc: "/assets/dot.png",
    Img: "/assets/Milwaukee_Bucks.jpeg",
  },

  // Southeast Division
  {
    id: 11,
    conference: "Eastern",
    division: "Southeast",
    title: "Atlanta Hawks",
    win: 63.9,
    offense: 87,
    defence: 82,
    pt: 70.2,
    ast: 76.5,
    reb: 71.0,
    icon: "/assets/starIcon.png",
    iconSrc: "/assets/dot.png",
    Img: "/assets/Atlanta_Hawks.png",
  },
  {
    id: 12,
    conference: "Eastern",
    division: "Southeast",
    title: "Charlotte Hornets",
    win: 55.1,
    offense: 82,
    defence: 79,
    pt: 66.1,
    ast: 72.9,
    reb: 69.4,
    icon: "/assets/starIcon.png",
    iconSrc: "/assets/dot.png",
    Img: "/assets/Charlotte_Hornets.jpeg",
  },
  {
    id: 13,
    conference: "Eastern",
    division: "Southeast",
    title: "Miami Heat",
    win: 71.2,
    offense: 90,
    defence: 86,
    pt: 74.9,
    ast: 79.6,
    reb: 72.7,
    iconSrc: "/assets/dot.png",
    icon: "/assets/starIcon.png",
    Img: "/assets/Miami_Heat.jpeg",
  },
  {
    id: 14,
    conference: "Eastern",
    division: "Southeast",
    title: "Orlando Magic",
    win: 61.5,
    offense: 85,
    defence: 81,
    pt: 69.7,
    ast: 74.8,
    reb: 70.9,
    icon: "/assets/starIcon.png",
    iconSrc: "/assets/dot.png",
    Img: "/assets/Orlando_Magic.png",
  },
  {
    id: 15,
    conference: "Eastern",
    division: "Southeast",
    title: "Washington Wizards",
    win: 53.8,
    offense: 81,
    defence: 77,
    pt: 66.4,
    ast: 72.3,
    reb: 68.7,
    icon: "/assets/starIcon.png",
    iconSrc: "/assets/dot.png",
    Img: "/assets/Washington_Wizards.png",
  },

  // 🏀 Western Conference
  // Northwest Division
  {
    id: 16,
    conference: "Western",
    division: "Northwest",
    title: "Denver Nuggets",
    win: 77.1,
    offense: 93,
    defence: 88,
    pt: 78.0,
    ast: 82.5,
    reb: 76.1,
    icon: "/assets/starIcon.png",
    iconSrc: "/assets/dot.png",
    Img: "/assets/Denver_Nuggets.png",
  },
  {
    id: 17,
    conference: "Western",
    division: "Northwest",
    title: "Minnesota Timberwolves",
    win: 68.4,
    offense: 89,
    defence: 84,
    pt: 73.5,
    ast: 78.3,
    reb: 72.4,
    icon: "/assets/starIcon.png",
    iconSrc: "/assets/dot.png",
    Img: "/assets/Minnesota_Timberwolves.jpeg",
  },
  {
    id: 18,
    conference: "Western",
    division: "Northwest",
    title: "Oklahoma City Thunder",
    win: 72.9,
    offense: 91,
    defence: 87,
    pt: 75.8,
    ast: 80.1,
    reb: 73.2,
    icon: "/assets/starIcon.png",
    iconSrc: "/assets/dot.png",
    Img: "/assets/Oklahoma_City_Thunder.png",
  },
  {
    id: 19,
    conference: "Western",
    division: "Northwest",
    title: "Portland Trail Blazers",
    win: 59.4,
    offense: 84,
    defence: 80,
    pt: 68.7,
    ast: 73.9,
    reb: 70.1,
    icon: "/assets/starIcon.png",
    iconSrc: "/assets/dot.png",
    Img: "/assets/Portland_Trail_Blazers.png",
  },
  {
    id: 20,
    conference: "Western",
    division: "Northwest",
    title: "Utah Jazz",
    win: 62.2,
    offense: 86,
    defence: 82,
    pt: 70.5,
    ast: 75.2,
    reb: 71.8,
    icon: "/assets/starIcon.png",
    iconSrc: "/assets/dot.png",
    Img: "/assets/Utah_Jazz.png",
  },

  // Pacific Division
  {
    id: 21,
    conference: "Western",
    division: "Pacific",
    title: "Golden State Warriors",
    win: 73.7,
    offense: 92,
    defence: 86,
    pt: 76.2,
    ast: 81.7,
    reb: 74.1,
    icon: "/assets/starIcon.png",
    iconSrc: "/assets/dot.png",
    Img: "/assets/Golden_State_Warriors.png",
  },
  {
    id: 22,
    conference: "Western",
    division: "Pacific",
    title: "LA Clippers",
    win: 71.9,
    offense: 91,
    defence: 85,
    pt: 75.3,
    ast: 80.9,
    reb: 73.5,
    icon: "/assets/starIcon.png",
    iconSrc: "/assets/dot.png",
    Img: "/assets/LA_Clippers.png",
  },
  {
    id: 23,
    conference: "Western",
    division: "Pacific",
    title: "Los Angeles Lakers",
    win: 70.4,
    offense: 90,
    defence: 84,
    pt: 74.8,
    ast: 79.8,
    reb: 72.9,
    icon: "/assets/starIcon.png",
    iconSrc: "/assets/dot.png",
    Img: "/assets/Los_Angeles_Lakers.png",
  },
  {
    id: 24,
    conference: "Western",
    division: "Pacific",
    title: "Phoenix Suns",
    win: 72.8,
    offense: 91,
    defence: 86,
    pt: 75.9,
    ast: 80.7,
    reb: 73.1,
    icon: "/assets/starIcon.png",
    iconSrc: "/assets/dot.png",
    Img: "/assets/Phoenix_Suns.png",
  },
  {
    id: 25,
    conference: "Western",
    division: "Pacific",
    title: "Sacramento Kings",
    win: 69.2,
    offense: 89,
    defence: 83,
    pt: 73.7,
    ast: 78.9,
    reb: 72.3,
    icon: "/assets/starIcon.png",
    iconSrc: "/assets/dot.png",
    Img: "/assets/Sacramento_Kings.png",
  },

  // Southwest Division
  {
    id: 26,
    conference: "Western",
    division: "Southwest",
    title: "Dallas Mavericks",
    win: 68.6,
    offense: 89,
    defence: 83,
    pt: 73.4,
    ast: 78.2,
    reb: 72.1,
    iconSrc: "/assets/dot.png",
    icon: "/assets/starIcon.png",
    Img: "/assets/Dallas_Mavericks.png",
  },
  {
    id: 27,
    conference: "Western",
    division: "Southwest",
    title: "Houston Rockets",
    win: 65.3,
    offense: 88,
    defence: 82,
    pt: 72.1,
    ast: 77.6,
    reb: 71.4,
    icon: "/assets/starIcon.png",
    iconSrc: "/assets/dot.png",
    Img: "/assets/Houston_Rockets.jpeg",
  },
  {
    id: 28,
    conference: "Western",
    division: "Southwest",
    title: "Memphis Grizzlies",
    win: 67.1,
    offense: 89,
    defence: 83,
    pt: 73.2,
    ast: 78.1,
    reb: 71.9,
    iconSrc: "/assets/dot.png",
    icon: "/assets/starIcon.png",
    Img: "/assets/Memphis_Grizzlies.png",
  },
  {
    id: 29,
    conference: "Western",
    division: "Southwest",
    title: "New Orleans Pelicans",
    win: 66.8,
    offense: 88,
    defence: 82,
    pt: 72.6,
    ast: 77.4,
    reb: 71.6,
    icon: "/assets/starIcon.png",
    iconSrc: "/assets/dot.png",
    Img: "/assets/New_Orleans_Pelicans.png",
  },
  {
    id: 30,
    conference: "Western",
    division: "Southwest",
    title: "San Antonio Spurs",
    win: 61.9,
    offense: 85,
    defence: 80,
    pt: 70.1,
    ast: 75.1,
    reb: 70.5,
    icon: "/assets/starIcon.png",
    iconSrc: "/assets/dot.png",
    Img: "/assets/San_Antonio_Spurs.png",
  },
];
